name: 'Test action'
on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - run: |
          echo "checks"

  plan:
    runs-on: ubuntu-latest
    needs: [ checks ]
    environment: 'production'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - run: |
          echo "plan"

  deploy:
    runs-on: ubuntu-latest
    needs: [ plan ]
    environment: 'production'
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - run: |
          echo "apply"
